from fastapi import FastAPI, UploadFile, File, HTTPException, Form
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any, Union, Tuple
import uvicorn
from dotenv import load_dotenv
import os
import logging
from pathlib import Path
import shutil

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Load environment variables
load_dotenv()

# Validate environment variables
if not os.getenv("OPENAI_API_KEY"):
    raise ValueError("OPENAI_API_KEY environment variable is not set")

# Initialize components
try:
    logger.info("Initializing RAGPipeline...")
    from .rag_pipeline import RAGPipeline
    rag_pipeline = RAGPipeline()
    logger.info("RAGPipeline initialized successfully")

    logger.info("Initializing DocumentProcessor...")
    from .document_processor import DocumentProcessor
    doc_processor = DocumentProcessor()
    logger.info("DocumentProcessor initialized successfully")
except Exception as e:
    logger.error(f"Error during initialization: {str(e)}")
    raise

# Initialize FastAPI app
app = FastAPI(
    title="Notebook LLM",
    description="A smart notebook application with LLM capabilities",
    version="1.0.0"
)

# Configure CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, replace with specific origins
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

from app.rag_pipeline import RAGPipeline
from app.query_decomposition_agent import QueryDecompositionAgent
from app.summarization_agent import SummarizationAgent
from app.relationship_mapping_agent import RelationshipMappingAgent
import os

# Initialize the RAG pipeline and the Agents
rag_pipeline = RAGPipeline()
query_agent = QueryDecompositionAgent(llm=rag_pipeline.llm)
summarization_agent = SummarizationAgent(llm=rag_pipeline.llm)
relationship_agent = RelationshipMappingAgent(llm=rag_pipeline.llm)


# Ensure the 'uploads' directory exists
UPLOAD_DIR = Path("uploads")
UPLOAD_DIR.mkdir(exist_ok=True)


class QueryRequest(BaseModel):
    query: str


class QueryResponse(BaseModel):
    answer: str
    sources: List[Dict[str, Any]]


class DecomposedQueryResponse(BaseModel):
    final_answer: str
    intermediate_steps: List[Tuple[str, str]]
    source_documents: List[Dict[str, Any]]


class DocumentResponse(BaseModel):
    message: str
    filename: str


class SummaryResponse(BaseModel):
    summary: str


class GraphResponse(BaseModel):
    nodes: List[Dict[str, Any]]
    edges: List[Dict[str, Any]]


@app.post("/upload/", response_model=DocumentResponse)
async def upload_document(file: UploadFile = File(...)):
    """
    Handles file uploads, processes them, and adds them to the RAG pipeline.
    """
    if not file.filename:
        raise HTTPException(status_code=400, detail="No file name provided.")

    file_path = UPLOAD_DIR / file.filename
    try:
        with open(file_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)

        rag_pipeline.add_document(str(file_path))

        return DocumentResponse(
            message="File processed and added to pipeline successfully.",
            filename=file.filename
        )
    except Exception as e:
        logger.error(f"Upload failed: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to process file: {str(e)}")


@app.post("/query/", response_model=QueryResponse)
async def query_pipeline(request: QueryRequest):
    """
    Receives a user's query and returns the answer generated by the RAG pipeline.
    """
    try:
        result = rag_pipeline.query(request.query)
        # Pydantic cannot directly serialize LangChain's Document objects
        # so we convert them to dicts first.
        sources = [vars(doc) for doc in result["source_documents"]]
        return QueryResponse(answer=result["answer"], sources=sources)
    except Exception as e:
        logger.error(f"Query failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/decomposed_query/", response_model=DecomposedQueryResponse)
async def decomposed_query(request: QueryRequest):
    """
    Handles complex queries by decomposing them into sub-queries,
    executing them, and synthesizing a final answer.
    """
    try:
        result = query_agent.execute_plan(request.query, rag_pipeline)
        
        # Serialize the source documents
        result["source_documents"] = [vars(doc) for doc in result["source_documents"]]
        
        return DecomposedQueryResponse(**result)
    except Exception as e:
        logger.error(f"Decomposed query failed: {e}")
        raise HTTPException(status_code=500, detail=f"Decomposed query failed: {str(e)}")


@app.post("/summarize/", response_model=SummaryResponse)
async def summarize_documents():
    """
    Generates a summary of all documents currently in the pipeline.
    """
    try:
        summary = summarization_agent.summarize(rag_pipeline)
        return SummaryResponse(summary=summary)
    except Exception as e:
        logger.error(f"Summarization failed: {e}")
        raise HTTPException(status_code=500, detail=f"Summarization failed: {str(e)}")


@app.post("/map_relationships/", response_model=GraphResponse)
async def map_relationships():
    """
    Extracts entities and relationships from all documents in the pipeline
    and returns them as a graph.
    """
    try:
        graph = relationship_agent.extract_graph(rag_pipeline)
        graph_json = relationship_agent.to_json(graph)
        return GraphResponse(**graph_json)
    except Exception as e:
        logger.error(f"Relationship mapping failed: {e}")
        raise HTTPException(status_code=500, detail=f"Relationship mapping failed: {str(e)}")


@app.post("/multimodal_query/")
async def multimodal_query(file: UploadFile = File(...), query: str = Form(...)):
    if not file.filename:
        raise HTTPException(status_code=400, detail="No file name provided.")

    file_path = UPLOAD_DIR / file.filename
    try:
        with open(file_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)

        content, metadata = rag_pipeline.document_processor.process_file(str(file_path))

        image_analysis_results = []
        if "images" in metadata and metadata["images"]:
            for image_path in metadata["images"]:
                description = rag_pipeline.vision_analyzer.analyze_image(image_path, query)
                image_analysis_results.append({
                    "image": image_path,
                    "analysis": description
                })

        # Combine text content with image analysis for the final answer
        combined_context = content
        if image_analysis_results:
            descriptions = "\n".join([res["analysis"] for res in image_analysis_results])
            combined_context += f"\n\n--- Image Analysis ---\n{descriptions}"

        final_answer = rag_pipeline.llm.invoke(f"Based on the following context, answer the query.\n\nContext:\n{combined_context}\n\nQuery: {query}")

        return {
            "query": query,
            "document_content": content,
            "image_analysis": image_analysis_results,
            "final_answer": final_answer.content
        }

    except Exception as e:
        logger.error(f"Multimodal query failed: {e}")
        raise HTTPException(status_code=500, detail=f"Multimodal query failed: {str(e)}")

if __name__ == "__main__":
    # Load existing vector store if available
    vector_store_path = Path("vector_store")
    if vector_store_path.exists():
        rag_pipeline.load_vector_store()
    
    uvicorn.run("app.main:app", host="0.0.0.0", port=8000, reload=True) 